[package]
name = "blue_engine"
version = "0.1.3"
authors = ["Elham Aryanpur <elhamaryanpur5@gmail.com>"]
edition = "2018"
description = "General-Purpose, Easy-to-use, Fast, Extendable, Secure, And Portable Graphics Engine"
documentation = "https://github.com/BlueMazar/BlueEngine/wiki"
repository = "https://github.com/BlueMazar/BlueEngine"
keywords = ["gamedev", "graphics", "3D", "2D", "game"]
categories = ["game-development", "gui", "graphics", "rendering"]
license-file = "LICENSE.txt"

[lib]
name = "blue_engine"
crate-type = ["rlib"]

[dependencies]
winit = "0.25.0"
cgmath = "0.18.0"
futures = "0.3.16"
image = "0.23.14"
bytemuck = { version = "1.7.2", features = [ "derive" ] }
winit_input_helper = "0.10.0"
anyhow = "1.0.42"
fontdue = "0.5.2"
env_logger = "0.9.0"

[dependencies.wgpu]
version = "0.9.0"
features = []
