[package]
name = "blue_engine"
version = "0.1.0"
authors = ["elham <elhamaryanpur5@gmail.com>"]
edition = "2018"

[dependencies]
winit = "*"
cgmath = "*"
futures = "*"
image = "*"
bytemuck = { version = "*", features = [ "derive" ] }
winit_input_helper = "*"

[dependencies.wgpu]
version = "*"
features = ["vulkan-portability"]

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
