[package]
name = "blue_engine"
version = "0.5.17"
authors = ["Elham Aryanpur <elhamaryanpur5@gmail.com>"]
edition = "2021"
description = "General-Purpose, Easy-to-use, Fast, and Portable graphics engine"
documentation = "https://aryanpurtech.github.io/BlueEngineDocs/"
repository = "https://github.com/AryanpurTech/BlueEngine"
keywords = ["gamedev", "graphics", "3D", "2D"]
categories = ["game-development", "gui", "graphics", "rendering"]
license = "Apache-2.0"
exclude = ["/examples"]

[lib]
name = "blue_engine"

[features]
default = ["debug"]
debug = ["dep:env_logger"]
android = ["dep:log", "dep:android_logger"]
android_native_activity = ["winit/android-native-activity"]
android_game_activity = ["winit/android-game-activity"]

[dependencies]
image = { version = "0.25.2" }
pollster = "0.3"
winit = { version = "0.30", features = ["rwh_06"] }
wgpu = { version = "22.1.0" }
bytemuck = { version = "1.16", features = ["derive"] }
eyre = "0.6"
downcast = "0.11"
nalgebra-glm = "0.19"
# debug logs
env_logger = { version = "0.11", optional = true }
# android
log = { version = "0.4", optional = true }
android_logger = { version = "0.14", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = { version = "22.1.0", features = ["webgl"] }

# Smallest possible release build
#
#[profile.release]
#opt-level = "z"
#panic = "abort"
#lto = true
#codegen-units = 1
#overflow-checks = false
#debug-assertions = false
#strip = "debuginfo"
#[profile.release.package."*"]
#opt-level = "z"
#codegen-units = 1

# ========== EXAMPLES ========== #

# SHAPES
[[example]]
name = "triangle"
path = "examples/shapes/triangle.rs"

[[example]]
name = "square"
path = "examples/shapes/square.rs"

[[example]]
name = "cube"
path = "examples/shapes/cube.rs"

# CAMERA
[[example]]
name = "rotate_around"
path = "examples/camera/rotate_around.rs"

# Utils
[[example]]
name = "resource_sharing"
path = "examples/utils/resource_sharing.rs"

[[example]]
name = "instancing"
path = "examples/utils/instancing.rs"

[[example]]
name = "render_order"
path = "examples/utils/render_order.rs"

[[example]]
name = "wireframe"
path = "examples/utils/wireframe.rs"

[[example]]
name = "scissor"
path = "examples/utils/scissor.rs"

[[example]]
name = "clear_color"
path = "examples/utils/clear_color.rs"

[[example]]
name = "signals"
path = "examples/utils/signals.rs"

# Development ONLY
[[example]]
name = "dev"
path = "examples/dev/dev.rs"
