[package]
name = "blue_engine"
version = "0.1.87"
authors = ["Elham Aryanpur <elhamaryanpur5@gmail.com>"]
edition = "2018"
description = "General-Purpose, Easy-to-use, Fast, Secure, and Portable graphics engine"
documentation = "https://github.com/ElhamAryanpur/BlueEngine/wiki"
repository = "https://github.com/ElhamAryanpur/BlueEngine"
keywords = ["gamedev", "graphics", "3D", "2D", "game"]
categories = ["game-development", "gui", "graphics", "rendering"]
license = "Apache-2.0"
resolver = "2"

[lib]
name = "blue_engine"
crate-type = ["rlib"]

[dependencies]
winit = "0.25.0"
futures = "0.3.17"
image = "0.23.14"
bytemuck = { version = "1.7.2", features = [ "derive" ] }
winit_input_helper = "0.10.0"
anyhow = "1.0.44"
fontdue = "0.5.2"
env_logger = "0.9.0"
glm = "0.2.3"
wgpu = "0.10.1"


# ========== EXAMPLES ========== #

# SHAPES
[[example]]
name = "triangle"
path = "examples/shapes/triangle.rs"

[[example]]
name = "square"
path = "examples/shapes/square.rs"

# CAMERA
[[example]]
name = "rotate_around"
path = "examples/camera/rotate_around.rs"

# Development ONLY
[[example]]
name = "dev"
path = "examples/dev/dev.rs"
