[package]
name = "blue_engine"
version = "0.1.0"
authors = ["elham <elhamaryanpur5@gmail.com>"]
edition = "2018"

[dependencies]
image = "*"
winit = "*"
cgmath = "*"
env_logger = "*"
log = "*"
futures = "*"
anyhow = "1.0"
fs_extra = "1.1"
glob = "0.3"
shaderc = "*"
sled = "*"

[dependencies.wgpu]
version = "*"
features = ["vulkan-portability"]

[profile.release]
lto = true
opt-level = 3
