[package]
name = "blue_engine"
version = "0.3.3"
authors = ["Elham Aryanpur <elhamaryanpur5@gmail.com>"]
edition = "2018"
description = "General-Purpose, Easy-to-use, Fast, Secure, and Portable graphics engine"
documentation = "https://github.com/ElhamAryanpur/BlueEngine/wiki"
repository = "https://github.com/ElhamAryanpur/BlueEngine"
keywords = ["gamedev", "graphics", "3D", "2D", "game"]
categories = ["game-development", "gui", "graphics", "rendering"]
license = "Apache-2.0"
resolver = "2"

[lib]
name = "blue_engine"
crate-type = ["rlib"]

[features]
default = ["model_loader"]
NON_FILL_POLYGON_MODE = []
model_loader = ["dep:gltf"]

[dependencies]
pollster = "0.2.5"
winit = "0.26.1"
image = "0.24.1"
bytemuck = { version = "1.7.2", features = [ "derive" ] }
winit_input_helper = "0.12.0"
anyhow = "1.0.44"
fontdue = "0.7.2"
env_logger = "0.9.0"
wgpu = "0.10.2"
nalgebra-glm = "0.16.0"
gltf = {version="1.0.0", optional = true }

# ========== EXAMPLES ========== #

# SHAPES
[[example]]
name = "triangle"
path = "examples/shapes/triangle.rs"

[[example]]
name = "square"
path = "examples/shapes/square.rs"

[[example]]
name = "cube"
path = "examples/shapes/cube.rs"

# CAMERA
[[example]]
name = "rotate_around"
path = "examples/camera/rotate_around.rs"

[[example]]
name = "fly_camera"
path = "examples/camera/fly_camera.rs"

# Development ONLY
[[example]]
name = "dev"
path = "examples/dev/dev.rs"
