[package]
name = "blue_engine"
version = "0.1.0"
authors = ["elham <elhamaryanpur5@gmail.com>"]
edition = "2018"

[dependencies]
image = "*"
winit = "*"
cgmath = "*"
env_logger = "*"
log = "*"
futures = "*"

[dependencies.wgpu]
version = "*"
features = ["vulkan-portability"]
 
[profile.release]
lto = true
opt-level = "3"
