[package]
name = "blue_engine_core"
version = "0.1.0"
authors = ["elham <elhamaryanpur5@gmail.com>"]
edition = "2018"

[lib]
name = "blue_engine_core"
crate-type = ["rlib"]

[dependencies]
winit = "*"
cgmath = "*"
futures = "*"
image = "*"
bytemuck = { version = "*", features = [ "derive" ] }
winit_input_helper = "*"
anyhow = "*"

[dependencies.wgpu]
version = "*"
features = ["vulkan-portability"]
