[package]
name = "blue_engine"
version = "0.4.29"
authors = ["Elham Aryanpur <elhamaryanpur5@gmail.com>"]
edition = "2021"
description = "General-Purpose, Easy-to-use, Fast, and Portable graphics engine"
documentation = "https://aryanpurtech.github.io/BlueEngineDocs/"
repository = "https://github.com/AryanpurTech/BlueEngine"
keywords = ["gamedev", "graphics", "3D", "2D"]
categories = ["game-development", "gui", "graphics", "rendering"]
license = "Apache-2.0"

[lib]
name = "blue_engine"

[features]
default = ["debug"]
debug = ["dep:env_logger"]
android = ["dep:log", "dep:android_logger"]
NON_FILL_POLYGON_MODE = []

[dependencies]
image = { version = "0.24" }
futures = "0.3"
winit = "0.28"
bytemuck = { version = "1.13", features = ["derive"] }
winit_input_helper = "0.14"
anyhow = "1.0"
wgpu = { version = "0.17.0" }
downcast = "0.11"
nalgebra-glm = "0.18"
# debug logs
env_logger = { version = "0.10", optional = true }
# android
log = { version = "0.4", optional = true }
android_logger = { version = "0.13", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = { version = "0.17", features = ["webgl"] }

# ========== EXAMPLES ========== #

# SHAPES
[[example]]
name = "triangle"
path = "examples/shapes/triangle.rs"

[[example]]
name = "square"
path = "examples/shapes/square.rs"

[[example]]
name = "cube"
path = "examples/shapes/cube.rs"

# CAMERA
[[example]]
name = "rotate_around"
path = "examples/camera/rotate_around.rs"

[[example]]
name = "fly_camera"
path = "examples/camera/fly_camera.rs"

# GUI
[[example]]
name = "hello_gui"
path = "examples/gui/hello_gui.rs"

[[example]]
name = "styling_gui"
path = "examples/gui/styling.rs"

# Development ONLY
[[example]]
name = "dev"
path = "examples/dev/dev.rs"
